/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "libsoup-2.4"

#define HAVE_CURL

#define HAVE_GMTIME_R 1

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_VERSION "2.67.92"

