-- Configuration
libUtilLinux_extradir = "Libs/UtilLinux/extra/"
libUtilLinux_origdir = "Libs/UtilLinux/orig/"
libUtilLinux_srcdir = libUtilLinux_origdir
libUtilLinux_incdir = libUtilLinux_origdir

-- Includes
libUtilLinux_includedirs = {
    libUtilLinux_incdir,
    libUtilLinux_incdir .. "lib/",
    libUtilLinux_incdir .. "libblkid/",
    libUtilLinux_incdir .. "libmount/",
    libUtilLinux_incdir .. "libuuid/"
}

-- Defines
libUtilLinux_defines = {
    "HAVE_CONFIG_H",
    "_DEFAULT_SOURCE",
    "LOCALEDIR=\"locale\"",
    "_PATH_RUNSTATEDIR=\"runstate\""
}
libUtilLinux_debugdefines = {
}
libUtilLinux_releasedefines = {
}

-- Options
libUtilLinux_buildoptions = {
    "-fsigned-char",
    "-fno-common"
}
libUtilLinux_linkoptions = {
}

-- Libs
libUtilLinux_libs = {
}

-- Sources
libUtilLinux_sources = {
    libUtilLinux_srcdir .. "lib/blkdev.c",
    libUtilLinux_srcdir .. "lib/canonicalize.c",
    libUtilLinux_srcdir .. "lib/crc32.c",
    libUtilLinux_srcdir .. "lib/crc32c.c",
    libUtilLinux_srcdir .. "lib/env.c",
    libUtilLinux_srcdir .. "lib/idcache.c",
    libUtilLinux_srcdir .. "lib/fileutils.c",
    libUtilLinux_srcdir .. "lib/ismounted.c",
    libUtilLinux_srcdir .. "lib/color-names.c",
    libUtilLinux_srcdir .. "lib/mangle.c",
    libUtilLinux_srcdir .. "lib/match.c",
    libUtilLinux_srcdir .. "lib/mbsalign.c",
    libUtilLinux_srcdir .. "lib/mbsedit.c",
    libUtilLinux_srcdir .. "lib/md5.c",
    libUtilLinux_srcdir .. "lib/pager.c",
    libUtilLinux_srcdir .. "lib/parse-date.c",
    libUtilLinux_srcdir .. "lib/pwdutils.c",
    libUtilLinux_srcdir .. "lib/randutils.c",
    libUtilLinux_srcdir .. "lib/setproctitle.c",
    libUtilLinux_srcdir .. "lib/strutils.c",
    libUtilLinux_srcdir .. "lib/timeutils.c",
    libUtilLinux_srcdir .. "lib/ttyutils.c",
    libUtilLinux_srcdir .. "lib/exec_shell.c",
    libUtilLinux_srcdir .. "lib/strv.c",
    libUtilLinux_srcdir .. "lib/sha1.c",
    libUtilLinux_srcdir .. "lib/signames.c",
    libUtilLinux_srcdir .. "lib/caputils.c",
    libUtilLinux_srcdir .. "lib/linux_version.c",
    libUtilLinux_srcdir .. "lib/loopdev.c",
    libUtilLinux_srcdir .. "lib/plymouth-ctrl.c",
    libUtilLinux_srcdir .. "lib/cpuset.c",
    libUtilLinux_srcdir .. "lib/path.c",
    libUtilLinux_srcdir .. "lib/procutils.c",
    libUtilLinux_srcdir .. "lib/sysfs.c",
    libUtilLinux_srcdir .. "libmount/src/cache.c",
    libUtilLinux_srcdir .. "libmount/src/fs.c",
    libUtilLinux_srcdir .. "libmount/src/init.c",
    libUtilLinux_srcdir .. "libmount/src/iter.c",
    libUtilLinux_srcdir .. "libmount/src/lock.c",
    libUtilLinux_srcdir .. "libmount/src/optmap.c",
    libUtilLinux_srcdir .. "libmount/src/optstr.c",
    libUtilLinux_srcdir .. "libmount/src/tab.c",
    libUtilLinux_srcdir .. "libmount/src/tab_diff.c",
    libUtilLinux_srcdir .. "libmount/src/tab_parse.c",
    libUtilLinux_srcdir .. "libmount/src/tab_update.c",
    libUtilLinux_srcdir .. "libmount/src/test.c",
    libUtilLinux_srcdir .. "libmount/src/utils.c",
    libUtilLinux_srcdir .. "libmount/src/version.c",
    libUtilLinux_srcdir .. "libmount/src/context.c",
    libUtilLinux_srcdir .. "libmount/src/context_loopdev.c",
    libUtilLinux_srcdir .. "libmount/src/context_mount.c",
    libUtilLinux_srcdir .. "libmount/src/context_umount.c",
    libUtilLinux_srcdir .. "libmount/src/monitor.c",
    libUtilLinux_srcdir .. "libmount/src/btrfs.c",
    libUtilLinux_srcdir .. "libblkid/src/init.c",
    libUtilLinux_srcdir .. "libblkid/src/cache.c",
    libUtilLinux_srcdir .. "libblkid/src/config.c",
    libUtilLinux_srcdir .. "libblkid/src/dev.c",
    libUtilLinux_srcdir .. "libblkid/src/devname.c",
    libUtilLinux_srcdir .. "libblkid/src/devno.c",
    libUtilLinux_srcdir .. "libblkid/src/encode.c",
    libUtilLinux_srcdir .. "libblkid/src/evaluate.c",
    libUtilLinux_srcdir .. "libblkid/src/getsize.c",
    libUtilLinux_srcdir .. "libblkid/src/llseek.c",
    libUtilLinux_srcdir .. "libblkid/src/probe.c",
    libUtilLinux_srcdir .. "libblkid/src/read.c",
    libUtilLinux_srcdir .. "libblkid/src/resolve.c",
    libUtilLinux_srcdir .. "libblkid/src/save.c",
    libUtilLinux_srcdir .. "libblkid/src/tag.c",
    libUtilLinux_srcdir .. "libblkid/src/verify.c",
    libUtilLinux_srcdir .. "libblkid/src/version.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/aix.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/atari.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/bsd.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/dos.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/gpt.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/mac.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/minix.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/partitions.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/sgi.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/solaris_x86.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/sun.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/ultrix.c",
    libUtilLinux_srcdir .. "libblkid/src/partitions/unixware.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/adaptec_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/apfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/bcache.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/befs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/bfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/bitlocker.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/bluestore.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/btrfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/cramfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ddf_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/drbd.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/drbdproxy_datalog.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/drbdmanage.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/exfat.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/exfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ext.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/f2fs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/gfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/hfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/highpoint_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/hpfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/iso9660.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/isw_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/jfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/jmicron_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/linux_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/lsi_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/luks.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/lvm.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/minix.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/mpool.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/netware.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/nilfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ntfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/refs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/nvidia_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ocfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/promise_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/reiserfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/romfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/silicon_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/squashfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/stratis.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/superblocks.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/swap.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/sysv.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ubi.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ubifs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/udf.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/ufs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/vdo.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/vfat.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/via_raid.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/vmfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/vxfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/xfs.c",
    libUtilLinux_srcdir .. "libblkid/src/superblocks/zfs.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/topology.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/dm.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/evms.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/ioctl.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/lvm.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/md.c",
    libUtilLinux_srcdir .. "libblkid/src/topology/sysfs.c",
    libUtilLinux_srcdir .. "libuuid/src/clear.c",
    libUtilLinux_srcdir .. "libuuid/src/compare.c",
    libUtilLinux_srcdir .. "libuuid/src/copy.c",
    libUtilLinux_srcdir .. "libuuid/src/gen_uuid.c",
    libUtilLinux_srcdir .. "libuuid/src/isnull.c",
    libUtilLinux_srcdir .. "libuuid/src/pack.c",
    libUtilLinux_srcdir .. "libuuid/src/parse.c",
    libUtilLinux_srcdir .. "libuuid/src/unpack.c",
    libUtilLinux_srcdir .. "libuuid/src/unparse.c",
    libUtilLinux_srcdir .. "libuuid/src/uuid_time.c",
    libUtilLinux_srcdir .. "libuuid/src/predefined.c",
}
