// Fyleria Engine
// Copyright © 2019 Go Go Gecko Productions

#ifndef _GECKO_UTILITY_JSON_H_
#define _GECKO_UTILITY_JSON_H_

// External includes
#include <nlohmann/json.hpp>

// Internal includes
#include "Utility/Types.h"
#include "Utility/Macros.h"

// Json defines
#define JsonParse nlohmann::json::parse
#define JsonToCBOR nlohmann::json::to_cbor
#define JsonToMsgPack nlohmann::json::to_msgpack
#define JsonFromCBOR nlohmann::json::from_cbor
#define JsonFromMsgPack nlohmann::json::from_msgpack

namespace Gecko
{

// Json basic types
typedef nlohmann::json Json;

// Json container types
typedef STDVector<Json> JsonArray;

// Json converters
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(Bool);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(Short);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(Int);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(Long);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(LongLong);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(UByte);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(UShort);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(UInt);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(ULong);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(ULongLong);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(Float);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(Double);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(LongDouble);
MAKE_JSON_BASIC_TYPE_CONVERTERS_DECL(String);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(BoolArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(ShortArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(IntArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(LongArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(LongLongArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(UByteArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(UShortArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(UIntArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(ULongArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(ULongLongArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(FloatArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(DoubleArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(LongDoubleArray);
MAKE_JSON_SEQUENCE_TYPE_CONVERTERS_DECL(StringArray);

};

#endif
