-- Configuration
libGtk_extradir = "Libs/C/Gtk/extra/"
libGtk_origdir = "Libs/C/Gtk/orig/"
libGtk_srcdir = libGtk_origdir
libGtk_incdir = libGtk_origdir

-- Includes
libGtk_includedirs = {
    libGtk_incdir,
    libGtk_incdir .. "gdk/",
    libGtk_incdir .. "gdk/x11/",
    libGtk_incdir .. "gtk/"
}
if os.host() == "linux" then
    table.insert(libGtk_includedirs, libGtk_extradir .. "linux/")
    table.insert(libGtk_includedirs, libGtk_extradir .. "linux/gdk/")
    table.insert(libGtk_includedirs, libGtk_extradir .. "linux/gtk/")
end

-- Defines
libGtk_defines = {
    "HAVE_CONFIG_H",
    "_FILE_OFFSET_BITS=64",
    "_GNU_SOURCE",
    "G_LOG_DOMAIN=\"Gtk\"",
    "G_LOG_STRUCTURED=1",
    "G_LOG_USE_STRUCTURED=1",
    "GTK_PRINT_BACKEND_ENABLE_UNSUPPORTED",
    "GLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_56",
    "GLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_58",
    "GTK_VERSION=\"3.24.11\"",
    "GTK_BINARY_VERSION=\"3.0.0\"",
    "GTK_HOST=\"gtk\"",
    "GTK_LIBDIR=\"lib\"",
    "GTK_LOCALEDIR=\"locale\"",
    "GTK_SYSCONFDIR=\"sysconf\"",
    "GTK_DATADIR=\"data\"",
    "GTK_PRINT_BACKENDS=\"file\"",
    "GTK_DATA_PREFIX=\"gtk\"",
    "X11_DATA_PREFIX=\"x11\"",
    "ISO_CODES_PREFIX=\"iso\"",
    "GDK_COMPILATION",
    "GTK_COMPILATION",
    "MULTIPRESS_LOCALEDIR=\"multipress_locale\"",
    "MULTIPRESS_CONFDIR=\"multipress_conf\"",
    "INCLUDE_IM_am_et",
    "INCLUDE_IM_cedilla",
    "INCLUDE_IM_cyrillic_translit",
    "INCLUDE_IM_inuktitut",
    "INCLUDE_IM_ipa",
    "INCLUDE_IM_multipress",
    "INCLUDE_IM_thai",
    "INCLUDE_IM_ti_er",
    "INCLUDE_IM_ti_et",
    "INCLUDE_IM_viqr",
    "INCLUDE_IM_xim",
}
libGtk_debugdefines = {
    "G_ENABLE_DEBUG",
    "G_ENABLE_CONSISTENCY_CHECKS"
}
libGtk_releasedefines = {
    "G_DISABLE_CAST_CHECKS"
}

-- Options
libGtk_buildoptions = {
    "-fno-strict-aliasing"
}
libGtk_linkoptions = {
}

-- Libs
libGtk_libs = {
    "Atk",
    "AtkBridge",
    "Cairo",
    "Epoxy",
    "GdkPixbuf",
    "Harfbuzz",
    "Pango"
}
if os.host() == "linux" then
    table.insert(libGtk_libs, "Xcomposite")
    table.insert(libGtk_libs, "Xcursor")
    table.insert(libGtk_libs, "Xdamage")
    table.insert(libGtk_libs, "Xi")
    table.insert(libGtk_libs, "Xrandr")
end

-- Sources
libGtk_sources = {
    libGtk_srcdir .. "gdk/deprecated/gdkcolor.c",
    libGtk_srcdir .. "gdk/gdkapplaunchcontext.c",
    libGtk_srcdir .. "gdk/gdk.c",
    libGtk_srcdir .. "gdk/gdkcairo.c",
    libGtk_srcdir .. "gdk/gdkcursor.c",
    libGtk_srcdir .. "gdk/gdkdeprecated.c",
    libGtk_srcdir .. "gdk/gdkdevice.c",
    libGtk_srcdir .. "gdk/gdkdevicemanager.c",
    libGtk_srcdir .. "gdk/gdkdevicepad.c",
    libGtk_srcdir .. "gdk/gdkdevicetool.c",
    libGtk_srcdir .. "gdk/gdkdisplay.c",
    libGtk_srcdir .. "gdk/gdkdisplaymanager.c",
    libGtk_srcdir .. "gdk/gdkdnd.c",
    libGtk_srcdir .. "gdk/gdkdrawingcontext.c",
    libGtk_srcdir .. "gdk/gdkevents.c",
    libGtk_srcdir .. "gdk/gdkframeclock.c",
    libGtk_srcdir .. "gdk/gdkframeclockidle.c",
    libGtk_srcdir .. "gdk/gdkframetimings.c",
    libGtk_srcdir .. "gdk/gdkgl.c",
    libGtk_srcdir .. "gdk/gdkglcontext.c",
    libGtk_srcdir .. "gdk/gdkglobals.c",
    libGtk_srcdir .. "gdk/gdkkeys.c",
    libGtk_srcdir .. "gdk/gdkkeyuni.c",
    libGtk_srcdir .. "gdk/gdkmonitor.c",
    libGtk_srcdir .. "gdk/gdkoffscreenwindow.c",
    libGtk_srcdir .. "gdk/gdkpango.c",
    libGtk_srcdir .. "gdk/gdkpixbuf-drawable.c",
    libGtk_srcdir .. "gdk/gdk-private.c",
    libGtk_srcdir .. "gdk/gdkprofiler.c",
    libGtk_srcdir .. "gdk/gdkproperty.c",
    libGtk_srcdir .. "gdk/gdkrectangle.c",
    libGtk_srcdir .. "gdk/gdkrgba.c",
    libGtk_srcdir .. "gdk/gdkscreen.c",
    libGtk_srcdir .. "gdk/gdkseat.c",
    libGtk_srcdir .. "gdk/gdkseatdefault.c",
    libGtk_srcdir .. "gdk/gdkselection.c",
    libGtk_srcdir .. "gdk/gdkvisual.c",
    libGtk_srcdir .. "gdk/gdkwindow.c",
    libGtk_srcdir .. "gdk/gdkwindowimpl.c",
    libGtk_srcdir .. "gdk/x11/gdkapplaunchcontext-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkasync.c",
    libGtk_srcdir .. "gdk/x11/gdkcursor-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdevice-core-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdevicemanager-core-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdevicemanager-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdevicemanager-xi2.c",
    libGtk_srcdir .. "gdk/x11/gdkdevice-xi2.c",
    libGtk_srcdir .. "gdk/x11/gdkdisplaymanager-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdisplaymanager-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdisplay-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkdnd-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkeventsource.c",
    libGtk_srcdir .. "gdk/x11/gdkeventtranslator.c",
    libGtk_srcdir .. "gdk/x11/gdkgeometry-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkglcontext-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkkeys-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkmain-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkmonitor-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkproperty-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkscreen-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkselection-x11.c",
    libGtk_srcdir .. "gdk/x11/gdktestutils-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkvisual-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkwindow-x11.c",
    libGtk_srcdir .. "gdk/x11/gdkxftdefaults.c",
    libGtk_srcdir .. "gdk/x11/gdkxid.c",
    libGtk_srcdir .. "gdk/x11/xsettings-client.c",
    libGtk_srcdir .. "gtk/a11y/gtkaccessibility.c",
    libGtk_srcdir .. "gtk/a11y/gtkaccessibilitymisc.c",
    libGtk_srcdir .. "gtk/a11y/gtkaccessibilityutil.c",
    libGtk_srcdir .. "gtk/a11y/gtkarrowaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkbooleancellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkbuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkcellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkcellaccessibleparent.c",
    libGtk_srcdir .. "gtk/a11y/gtkcheckmenuitemaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkcolorswatchaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkcomboboxaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkcontaineraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkcontainercellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkentryaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkexpanderaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkflowboxaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkflowboxchildaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkframeaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkheaderbaraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkiconviewaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkimageaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkimagecellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtklabelaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtklevelbaraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtklinkbuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtklistboxaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtklistboxrowaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtklockbuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkmenuaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkmenubuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkmenuitemaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkmenushellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtknotebookaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtknotebookpageaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkpanedaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkpopoveraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkprogressbaraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkradiobuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkradiomenuitemaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkrangeaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkrenderercellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkscaleaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkscalebuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkscrolledwindowaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkspinbuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkspinneraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkstackaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkstatusbaraccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkswitchaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtktextcellaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtktextviewaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtktogglebuttonaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtktoplevelaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtktreeviewaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkwidgetaccessible.c",
    libGtk_srcdir .. "gtk/a11y/gtkwindowaccessible.c",
    libGtk_srcdir .. "gtk/deprecated/gtkaction.c",
    libGtk_srcdir .. "gtk/deprecated/gtkactiongroup.c",
    libGtk_srcdir .. "gtk/deprecated/gtkactivatable.c",
    libGtk_srcdir .. "gtk/deprecated/gtkalignment.c",
    libGtk_srcdir .. "gtk/deprecated/gtkarrow.c",
    libGtk_srcdir .. "gtk/deprecated/gtkcolorsel.c",
    libGtk_srcdir .. "gtk/deprecated/gtkcolorseldialog.c",
    libGtk_srcdir .. "gtk/deprecated/gtkfontsel.c",
    libGtk_srcdir .. "gtk/deprecated/gtkgradient.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhandlebox.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhbbox.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhbox.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhpaned.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhscale.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhscrollbar.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhseparator.c",
    libGtk_srcdir .. "gtk/deprecated/gtkhsv.c",
    libGtk_srcdir .. "gtk/deprecated/gtkiconfactory.c",
    libGtk_srcdir .. "gtk/deprecated/gtkimagemenuitem.c",
    libGtk_srcdir .. "gtk/deprecated/gtkmisc.c",
    libGtk_srcdir .. "gtk/deprecated/gtknumerableicon.c",
    libGtk_srcdir .. "gtk/deprecated/gtkradioaction.c",
    libGtk_srcdir .. "gtk/deprecated/gtkrc.c",
    libGtk_srcdir .. "gtk/deprecated/gtkrecentaction.c",
    libGtk_srcdir .. "gtk/deprecated/gtkstatusicon.c",
    libGtk_srcdir .. "gtk/deprecated/gtkstock.c",
    libGtk_srcdir .. "gtk/deprecated/gtkstyle.c",
    libGtk_srcdir .. "gtk/deprecated/gtkstyleproperties.c",
    libGtk_srcdir .. "gtk/deprecated/gtksymboliccolor.c",
    libGtk_srcdir .. "gtk/deprecated/gtktable.c",
    libGtk_srcdir .. "gtk/deprecated/gtktearoffmenuitem.c",
    libGtk_srcdir .. "gtk/deprecated/gtkthemingengine.c",
    libGtk_srcdir .. "gtk/deprecated/gtktoggleaction.c",
    libGtk_srcdir .. "gtk/deprecated/gtktrayicon-x11.c",
    libGtk_srcdir .. "gtk/deprecated/gtkuimanager.c",
    libGtk_srcdir .. "gtk/deprecated/gtkvbbox.c",
    libGtk_srcdir .. "gtk/deprecated/gtkvbox.c",
    libGtk_srcdir .. "gtk/deprecated/gtkvpaned.c",
    libGtk_srcdir .. "gtk/deprecated/gtkvscale.c",
    libGtk_srcdir .. "gtk/deprecated/gtkvscrollbar.c",
    libGtk_srcdir .. "gtk/deprecated/gtkvseparator.c",
    libGtk_srcdir .. "gtk/fnmatch.c",
    libGtk_srcdir .. "gtk/gdkpixbufutils.c",
    libGtk_srcdir .. "gtk/gtkaboutdialog.c",
    libGtk_srcdir .. "gtk/gtkaccelgroup.c",
    libGtk_srcdir .. "gtk/gtkaccellabel.c",
    libGtk_srcdir .. "gtk/gtkaccelmap.c",
    libGtk_srcdir .. "gtk/gtkaccessible.c",
    libGtk_srcdir .. "gtk/gtkactionable.c",
    libGtk_srcdir .. "gtk/gtkactionbar.c",
    libGtk_srcdir .. "gtk/gtkactionhelper.c",
    libGtk_srcdir .. "gtk/gtkactionmuxer.c",
    libGtk_srcdir .. "gtk/gtkactionobservable.c",
    libGtk_srcdir .. "gtk/gtkactionobserver.c",
    libGtk_srcdir .. "gtk/gtkadjustment.c",
    libGtk_srcdir .. "gtk/gtkallocatedbitmask.c",
    libGtk_srcdir .. "gtk/gtkallocatedbitmask.c",
    libGtk_srcdir .. "gtk/gtkappchooserbutton.c",
    libGtk_srcdir .. "gtk/gtkappchooser.c",
    libGtk_srcdir .. "gtk/gtkappchooserdialog.c",
    libGtk_srcdir .. "gtk/gtkappchooserwidget.c",
    libGtk_srcdir .. "gtk/gtkapplicationaccels.c",
    libGtk_srcdir .. "gtk/gtkapplication.c",
    libGtk_srcdir .. "gtk/gtkapplication-dbus.c",
    libGtk_srcdir .. "gtk/gtkapplicationimpl.c",
    libGtk_srcdir .. "gtk/gtkapplicationwindow.c",
    libGtk_srcdir .. "gtk/gtkapplication-x11.c",
    libGtk_srcdir .. "gtk/gtkaspectframe.c",
    libGtk_srcdir .. "gtk/gtkassistant.c",
    libGtk_srcdir .. "gtk/gtkbbox.c",
    libGtk_srcdir .. "gtk/gtkbin.c",
    libGtk_srcdir .. "gtk/gtkbindings.c",
    libGtk_srcdir .. "gtk/gtkbookmarksmanager.c",
    libGtk_srcdir .. "gtk/gtkborder.c",
    libGtk_srcdir .. "gtk/gtkbox.c",
    libGtk_srcdir .. "gtk/gtkboxgadget.c",
    libGtk_srcdir .. "gtk/gtkbuildable.c",
    libGtk_srcdir .. "gtk/gtkbuilder.c",
    libGtk_srcdir .. "gtk/gtkbuilder-menus.c",
    libGtk_srcdir .. "gtk/gtkbuilderparser.c",
    libGtk_srcdir .. "gtk/gtkbuiltinicon.c",
    libGtk_srcdir .. "gtk/gtkbutton.c",
    libGtk_srcdir .. "gtk/gtkcairoblur.c",
    libGtk_srcdir .. "gtk/gtkcairoblur.c",
    libGtk_srcdir .. "gtk/gtkcalendar.c",
    libGtk_srcdir .. "gtk/gtkcellareabox.c",
    libGtk_srcdir .. "gtk/gtkcellareaboxcontext.c",
    libGtk_srcdir .. "gtk/gtkcellarea.c",
    libGtk_srcdir .. "gtk/gtkcellareacontext.c",
    libGtk_srcdir .. "gtk/gtkcelleditable.c",
    libGtk_srcdir .. "gtk/gtkcelllayout.c",
    libGtk_srcdir .. "gtk/gtkcellrendereraccel.c",
    libGtk_srcdir .. "gtk/gtkcellrenderer.c",
    libGtk_srcdir .. "gtk/gtkcellrenderercombo.c",
    libGtk_srcdir .. "gtk/gtkcellrendererpixbuf.c",
    libGtk_srcdir .. "gtk/gtkcellrendererprogress.c",
    libGtk_srcdir .. "gtk/gtkcellrendererspin.c",
    libGtk_srcdir .. "gtk/gtkcellrendererspinner.c",
    libGtk_srcdir .. "gtk/gtkcellrenderertext.c",
    libGtk_srcdir .. "gtk/gtkcellrenderertoggle.c",
    libGtk_srcdir .. "gtk/gtkcellview.c",
    libGtk_srcdir .. "gtk/gtkcheckbutton.c",
    libGtk_srcdir .. "gtk/gtkcheckmenuitem.c",
    libGtk_srcdir .. "gtk/gtkclipboard.c",
    libGtk_srcdir .. "gtk/gtkcolorbutton.c",
    libGtk_srcdir .. "gtk/gtkcolorchooser.c",
    libGtk_srcdir .. "gtk/gtkcolorchooserdialog.c",
    libGtk_srcdir .. "gtk/gtkcolorchooserwidget.c",
    libGtk_srcdir .. "gtk/gtkcoloreditor.c",
    libGtk_srcdir .. "gtk/gtkcolorpicker.c",
    libGtk_srcdir .. "gtk/gtkcolorpickerkwin.c",
    libGtk_srcdir .. "gtk/gtkcolorpickerportal.c",
    libGtk_srcdir .. "gtk/gtkcolorpickershell.c",
    libGtk_srcdir .. "gtk/gtkcolorplane.c",
    libGtk_srcdir .. "gtk/gtkcolorscale.c",
    libGtk_srcdir .. "gtk/gtkcolorswatch.c",
    libGtk_srcdir .. "gtk/gtkcolorutils.c",
    libGtk_srcdir .. "gtk/gtkcombobox.c",
    libGtk_srcdir .. "gtk/gtkcomboboxtext.c",
    libGtk_srcdir .. "gtk/gtkcomposetable.c",
    libGtk_srcdir .. "gtk/gtkcontainer.c",
    libGtk_srcdir .. "gtk/gtkcssanimatedstyle.c",
    libGtk_srcdir .. "gtk/gtkcssanimation.c",
    libGtk_srcdir .. "gtk/gtkcssarrayvalue.c",
    libGtk_srcdir .. "gtk/gtkcssbgsizevalue.c",
    libGtk_srcdir .. "gtk/gtkcssbordervalue.c",
    libGtk_srcdir .. "gtk/gtkcsscalcvalue.c",
    libGtk_srcdir .. "gtk/gtkcsscolorvalue.c",
    libGtk_srcdir .. "gtk/gtkcsscornervalue.c",
    libGtk_srcdir .. "gtk/gtkcsscustomgadget.c",
    libGtk_srcdir .. "gtk/gtkcsscustomproperty.c",
    libGtk_srcdir .. "gtk/gtkcssdimensionvalue.c",
    libGtk_srcdir .. "gtk/gtkcsseasevalue.c",
    libGtk_srcdir .. "gtk/gtkcssenginevalue.c",
    libGtk_srcdir .. "gtk/gtkcssenumvalue.c",
    libGtk_srcdir .. "gtk/gtkcssgadget.c",
    libGtk_srcdir .. "gtk/gtkcssiconthemevalue.c",
    libGtk_srcdir .. "gtk/gtkcssimagebuiltin.c",
    libGtk_srcdir .. "gtk/gtkcssimage.c",
    libGtk_srcdir .. "gtk/gtkcssimagecrossfade.c",
    libGtk_srcdir .. "gtk/gtkcssimagefallback.c",
    libGtk_srcdir .. "gtk/gtkcssimagegradient.c",
    libGtk_srcdir .. "gtk/gtkcssimageicontheme.c",
    libGtk_srcdir .. "gtk/gtkcssimagelinear.c",
    libGtk_srcdir .. "gtk/gtkcssimageradial.c",
    libGtk_srcdir .. "gtk/gtkcssimagerecolor.c",
    libGtk_srcdir .. "gtk/gtkcssimagescaled.c",
    libGtk_srcdir .. "gtk/gtkcssimagesurface.c",
    libGtk_srcdir .. "gtk/gtkcssimageurl.c",
    libGtk_srcdir .. "gtk/gtkcssimagevalue.c",
    libGtk_srcdir .. "gtk/gtkcssimagewin32.c",
    libGtk_srcdir .. "gtk/gtkcssinheritvalue.c",
    libGtk_srcdir .. "gtk/gtkcssinitialvalue.c",
    libGtk_srcdir .. "gtk/gtkcsskeyframes.c",
    libGtk_srcdir .. "gtk/gtkcsslookup.c",
    libGtk_srcdir .. "gtk/gtkcssmatcher.c",
    libGtk_srcdir .. "gtk/gtkcssnode.c",
    libGtk_srcdir .. "gtk/gtkcssnodedeclaration.c",
    libGtk_srcdir .. "gtk/gtkcssnodestylecache.c",
    libGtk_srcdir .. "gtk/gtkcssnumbervalue.c",
    libGtk_srcdir .. "gtk/gtkcsspalettevalue.c",
    libGtk_srcdir .. "gtk/gtkcssparser.c",
    libGtk_srcdir .. "gtk/gtkcsspathnode.c",
    libGtk_srcdir .. "gtk/gtkcsspositionvalue.c",
    libGtk_srcdir .. "gtk/gtkcssprovider.c",
    libGtk_srcdir .. "gtk/gtkcssrepeatvalue.c",
    libGtk_srcdir .. "gtk/gtkcssrgbavalue.c",
    libGtk_srcdir .. "gtk/gtkcsssection.c",
    libGtk_srcdir .. "gtk/gtkcssselector.c",
    libGtk_srcdir .. "gtk/gtkcssshadowsvalue.c",
    libGtk_srcdir .. "gtk/gtkcssshadowvalue.c",
    libGtk_srcdir .. "gtk/gtkcssshorthandproperty.c",
    libGtk_srcdir .. "gtk/gtkcssshorthandpropertyimpl.c",
    libGtk_srcdir .. "gtk/gtkcssstaticstyle.c",
    libGtk_srcdir .. "gtk/gtkcssstringvalue.c",
    libGtk_srcdir .. "gtk/gtkcssstyle.c",
    libGtk_srcdir .. "gtk/gtkcssstylechange.c",
    libGtk_srcdir .. "gtk/gtkcssstylefuncs.c",
    libGtk_srcdir .. "gtk/gtkcssstyleproperty.c",
    libGtk_srcdir .. "gtk/gtkcssstylepropertyimpl.c",
    libGtk_srcdir .. "gtk/gtkcsstransformvalue.c",
    libGtk_srcdir .. "gtk/gtkcsstransientnode.c",
    libGtk_srcdir .. "gtk/gtkcsstransition.c",
    libGtk_srcdir .. "gtk/gtkcsstypedvalue.c",
    libGtk_srcdir .. "gtk/gtkcsstypes.c",
    libGtk_srcdir .. "gtk/gtkcssunsetvalue.c",
    libGtk_srcdir .. "gtk/gtkcssvalue.c",
    libGtk_srcdir .. "gtk/gtkcsswidgetnode.c",
    libGtk_srcdir .. "gtk/gtkcsswin32sizevalue.c",
    libGtk_srcdir .. "gtk/gtkcustompaperunixdialog.c",
    libGtk_srcdir .. "gtk/gtkdialog.c",
    libGtk_srcdir .. "gtk/gtkdnd.c",
    libGtk_srcdir .. "gtk/gtkdragdest.c",
    libGtk_srcdir .. "gtk/gtkdragsource.c",
    libGtk_srcdir .. "gtk/gtkdrawingarea.c",
    libGtk_srcdir .. "gtk/gtkeditable.c",
    libGtk_srcdir .. "gtk/gtkemojichooser.c",
    libGtk_srcdir .. "gtk/gtkemojicompletion.c",
    libGtk_srcdir .. "gtk/gtkentrybuffer.c",
    libGtk_srcdir .. "gtk/gtkentry.c",
    libGtk_srcdir .. "gtk/gtkentrycompletion.c",
    libGtk_srcdir .. "gtk/gtkeventbox.c",
    libGtk_srcdir .. "gtk/gtkeventcontroller.c",
    libGtk_srcdir .. "gtk/gtkeventcontrollerkey.c",
    libGtk_srcdir .. "gtk/gtkeventcontrollermotion.c",
    libGtk_srcdir .. "gtk/gtkeventcontrollerscroll.c",
    libGtk_srcdir .. "gtk/gtkexpander.c",
    libGtk_srcdir .. "gtk/gtkfilechooserbutton.c",
    libGtk_srcdir .. "gtk/gtkfilechooser.c",
    libGtk_srcdir .. "gtk/gtkfilechooserdialog.c",
    libGtk_srcdir .. "gtk/gtkfilechooserembed.c",
    libGtk_srcdir .. "gtk/gtkfilechooserentry.c",
    libGtk_srcdir .. "gtk/gtkfilechoosernative.c",
    libGtk_srcdir .. "gtk/gtkfilechoosernativeportal.c",
    libGtk_srcdir .. "gtk/gtkfilechooserutils.c",
    libGtk_srcdir .. "gtk/gtkfilechooserwidget.c",
    libGtk_srcdir .. "gtk/gtkfilefilter.c",
    libGtk_srcdir .. "gtk/gtkfilesystem.c",
    libGtk_srcdir .. "gtk/gtkfilesystemmodel.c",
    libGtk_srcdir .. "gtk/gtkfixed.c",
    libGtk_srcdir .. "gtk/gtkflowbox.c",
    libGtk_srcdir .. "gtk/gtkfontbutton.c",
    libGtk_srcdir .. "gtk/gtkfontchooser.c",
    libGtk_srcdir .. "gtk/gtkfontchooserdialog.c",
    libGtk_srcdir .. "gtk/gtkfontchooserutils.c",
    libGtk_srcdir .. "gtk/gtkfontchooserwidget.c",
    libGtk_srcdir .. "gtk/gtkframe.c",
    libGtk_srcdir .. "gtk/gtkgesture.c",
    libGtk_srcdir .. "gtk/gtkgesturedrag.c",
    libGtk_srcdir .. "gtk/gtkgesturelongpress.c",
    libGtk_srcdir .. "gtk/gtkgesturemultipress.c",
    libGtk_srcdir .. "gtk/gtkgesturepan.c",
    libGtk_srcdir .. "gtk/gtkgesturerotate.c",
    libGtk_srcdir .. "gtk/gtkgesturesingle.c",
    libGtk_srcdir .. "gtk/gtkgesturestylus.c",
    libGtk_srcdir .. "gtk/gtkgestureswipe.c",
    libGtk_srcdir .. "gtk/gtkgesturezoom.c",
    libGtk_srcdir .. "gtk/gtkgladecatalog.c",
    libGtk_srcdir .. "gtk/gtkglarea.c",
    libGtk_srcdir .. "gtk/gtkgrid.c",
    libGtk_srcdir .. "gtk/gtkheaderbar.c",
    libGtk_srcdir .. "gtk/gtkhsla.c",
    libGtk_srcdir .. "gtk/gtkicon.c",
    libGtk_srcdir .. "gtk/gtkiconcache.c",
    libGtk_srcdir .. "gtk/gtkiconcachevalidator.c",
    libGtk_srcdir .. "gtk/gtkiconhelper.c",
    libGtk_srcdir .. "gtk/gtkicontheme.c",
    libGtk_srcdir .. "gtk/gtkiconview.c",
    libGtk_srcdir .. "gtk/gtkimage.c",
    libGtk_srcdir .. "gtk/gtkimagedefinition.c",
    libGtk_srcdir .. "gtk/gtkimcontext.c",
    libGtk_srcdir .. "gtk/gtkimcontextsimple.c",
    libGtk_srcdir .. "gtk/gtkimmodule.c",
    libGtk_srcdir .. "gtk/gtkimmulticontext.c",
    libGtk_srcdir .. "gtk/gtkinfobar.c",
    libGtk_srcdir .. "gtk/gtkinvisible.c",
    libGtk_srcdir .. "gtk/gtkkeyhash.c",
    libGtk_srcdir .. "gtk/gtkkeyhash.c",
    libGtk_srcdir .. "gtk/gtkkineticscrolling.c",
    libGtk_srcdir .. "gtk/gtklabel.c",
    libGtk_srcdir .. "gtk/gtklayout.c",
    libGtk_srcdir .. "gtk/gtklevelbar.c",
    libGtk_srcdir .. "gtk/gtklinkbutton.c",
    libGtk_srcdir .. "gtk/gtklistbox.c",
    libGtk_srcdir .. "gtk/gtkliststore.c",
    libGtk_srcdir .. "gtk/gtklockbutton.c",
    libGtk_srcdir .. "gtk/gtkmagnifier.c",
    libGtk_srcdir .. "gtk/gtkmain.c",
    libGtk_srcdir .. "gtk/gtkmenubar.c",
    libGtk_srcdir .. "gtk/gtkmenubutton.c",
    libGtk_srcdir .. "gtk/gtkmenu.c",
    libGtk_srcdir .. "gtk/gtkmenuitem.c",
    libGtk_srcdir .. "gtk/gtkmenusectionbox.c",
    libGtk_srcdir .. "gtk/gtkmenushell.c",
    libGtk_srcdir .. "gtk/gtkmenutoolbutton.c",
    libGtk_srcdir .. "gtk/gtkmenutracker.c",
    libGtk_srcdir .. "gtk/gtkmenutrackeritem.c",
    libGtk_srcdir .. "gtk/gtkmessagedialog.c",
    libGtk_srcdir .. "gtk/gtkmnemonichash.c",
    libGtk_srcdir .. "gtk/gtkmodelbutton.c",
    libGtk_srcdir .. "gtk/gtkmodelmenuitem.c",
    libGtk_srcdir .. "gtk/gtkmodifierstyle.c",
    libGtk_srcdir .. "gtk/gtkmodules.c",
    libGtk_srcdir .. "gtk/gtkmountoperation.c",
    libGtk_srcdir .. "gtk/gtkmountoperation-x11.c",
    libGtk_srcdir .. "gtk/gtknativedialog.c",
    libGtk_srcdir .. "gtk/gtknotebook.c",
    libGtk_srcdir .. "gtk/gtkoffscreenwindow.c",
    libGtk_srcdir .. "gtk/gtkorientable.c",
    libGtk_srcdir .. "gtk/gtkoverlay.c",
    libGtk_srcdir .. "gtk/gtkpadcontroller.c",
    libGtk_srcdir .. "gtk/gtkpagesetup.c",
    libGtk_srcdir .. "gtk/gtkpagesetupunixdialog.c",
    libGtk_srcdir .. "gtk/gtkpaned.c",
    libGtk_srcdir .. "gtk/gtkpango.c",
    libGtk_srcdir .. "gtk/gtkpapersize.c",
    libGtk_srcdir .. "gtk/gtkpathbar.c",
    libGtk_srcdir .. "gtk/gtkpixelcache.c",
    libGtk_srcdir .. "gtk/gtkplacessidebar.c",
    libGtk_srcdir .. "gtk/gtkplacesview.c",
    libGtk_srcdir .. "gtk/gtkplacesviewrow.c",
    libGtk_srcdir .. "gtk/gtkplug.c",
    libGtk_srcdir .. "gtk/gtkpopover.c",
    libGtk_srcdir .. "gtk/gtkpopovermenu.c",
    libGtk_srcdir .. "gtk/gtkprintbackend.c",
    libGtk_srcdir .. "gtk/gtkprintcontext.c",
    libGtk_srcdir .. "gtk/gtkprinter.c",
    libGtk_srcdir .. "gtk/gtkprinteroption.c",
    libGtk_srcdir .. "gtk/gtkprinteroptionset.c",
    libGtk_srcdir .. "gtk/gtkprinteroptionwidget.c",
    libGtk_srcdir .. "gtk/gtkprintjob.c",
    libGtk_srcdir .. "gtk/gtkprintoperation.c",
    libGtk_srcdir .. "gtk/gtkprintoperation-portal.c",
    libGtk_srcdir .. "gtk/gtkprintoperationpreview.c",
    libGtk_srcdir .. "gtk/gtkprintoperation-unix.c",
    libGtk_srcdir .. "gtk/gtkprintsettings.c",
    libGtk_srcdir .. "gtk/gtkprintunixdialog.c",
    libGtk_srcdir .. "gtk/gtkprintutils.c",
    libGtk_srcdir .. "gtk/gtkprivate.c",
    libGtk_srcdir .. "gtk/gtkprivate.c",
    libGtk_srcdir .. "gtk/gtkprogressbar.c",
    libGtk_srcdir .. "gtk/gtkprogresstracker.c",
    libGtk_srcdir .. "gtk/gtkquery.c",
    libGtk_srcdir .. "gtk/gtkradiobutton.c",
    libGtk_srcdir .. "gtk/gtkradiomenuitem.c",
    libGtk_srcdir .. "gtk/gtkradiotoolbutton.c",
    libGtk_srcdir .. "gtk/gtkrange.c",
    libGtk_srcdir .. "gtk/gtkrbtree.c",
    libGtk_srcdir .. "gtk/gtkrbtree.c",
    libGtk_srcdir .. "gtk/gtkrecentchooser.c",
    libGtk_srcdir .. "gtk/gtkrecentchooserdefault.c",
    libGtk_srcdir .. "gtk/gtkrecentchooserdialog.c",
    libGtk_srcdir .. "gtk/gtkrecentchoosermenu.c",
    libGtk_srcdir .. "gtk/gtkrecentchooserutils.c",
    libGtk_srcdir .. "gtk/gtkrecentchooserwidget.c",
    libGtk_srcdir .. "gtk/gtkrecentfilter.c",
    libGtk_srcdir .. "gtk/gtkrecentmanager.c",
    libGtk_srcdir .. "gtk/gtkrenderbackground.c",
    libGtk_srcdir .. "gtk/gtkrenderborder.c",
    libGtk_srcdir .. "gtk/gtkrender.c",
    libGtk_srcdir .. "gtk/gtkrendericon.c",
    libGtk_srcdir .. "gtk/gtkrevealer.c",
    libGtk_srcdir .. "gtk/gtkroundedbox.c",
    libGtk_srcdir .. "gtk/gtkscalebutton.c",
    libGtk_srcdir .. "gtk/gtkscale.c",
    libGtk_srcdir .. "gtk/gtkscrollable.c",
    libGtk_srcdir .. "gtk/gtkscrollbar.c",
    libGtk_srcdir .. "gtk/gtkscrolledwindow.c",
    libGtk_srcdir .. "gtk/gtksearchbar.c",
    libGtk_srcdir .. "gtk/gtksearchengine.c",
    libGtk_srcdir .. "gtk/gtksearchenginemodel.c",
    libGtk_srcdir .. "gtk/gtksearchenginesimple.c",
    libGtk_srcdir .. "gtk/gtksearchenginetracker.c",
    libGtk_srcdir .. "gtk/gtksearchentry.c",
    libGtk_srcdir .. "gtk/gtkselection.c",
    libGtk_srcdir .. "gtk/gtkseparator.c",
    libGtk_srcdir .. "gtk/gtkseparatormenuitem.c",
    libGtk_srcdir .. "gtk/gtkseparatortoolitem.c",
    libGtk_srcdir .. "gtk/gtksettings.c",
    libGtk_srcdir .. "gtk/gtkshortcutlabel.c",
    libGtk_srcdir .. "gtk/gtkshortcutsgroup.c",
    libGtk_srcdir .. "gtk/gtkshortcutssection.c",
    libGtk_srcdir .. "gtk/gtkshortcutsshortcut.c",
    libGtk_srcdir .. "gtk/gtkshortcutswindow.c",
    libGtk_srcdir .. "gtk/gtkshow.c",
    libGtk_srcdir .. "gtk/gtksidebarrow.c",
    libGtk_srcdir .. "gtk/gtksizegroup.c",
    libGtk_srcdir .. "gtk/gtksizerequest.c",
    libGtk_srcdir .. "gtk/gtksizerequestcache.c",
    libGtk_srcdir .. "gtk/gtksocket.c",
    libGtk_srcdir .. "gtk/gtkspinbutton.c",
    libGtk_srcdir .. "gtk/gtkspinner.c",
    libGtk_srcdir .. "gtk/gtkstack.c",
    libGtk_srcdir .. "gtk/gtkstacksidebar.c",
    libGtk_srcdir .. "gtk/gtkstackswitcher.c",
    libGtk_srcdir .. "gtk/gtkstatusbar.c",
    libGtk_srcdir .. "gtk/gtkstyleanimation.c",
    libGtk_srcdir .. "gtk/gtkstylecascade.c",
    libGtk_srcdir .. "gtk/gtkstylecontext.c",
    libGtk_srcdir .. "gtk/gtkstyleproperty.c",
    libGtk_srcdir .. "gtk/gtkstyleprovider.c",
    libGtk_srcdir .. "gtk/gtkstyleproviderprivate.c",
    libGtk_srcdir .. "gtk/gtkswitch.c",
    libGtk_srcdir .. "gtk/gtktestutils.c",
    libGtk_srcdir .. "gtk/gtktextattributes.c",
    libGtk_srcdir .. "gtk/gtktextbtree.c",
    libGtk_srcdir .. "gtk/gtktextbuffer.c",
    libGtk_srcdir .. "gtk/gtktextbufferrichtext.c",
    libGtk_srcdir .. "gtk/gtktextbufferserialize.c",
    libGtk_srcdir .. "gtk/gtktextchild.c",
    libGtk_srcdir .. "gtk/gtktextdisplay.c",
    libGtk_srcdir .. "gtk/gtktexthandle.c",
    libGtk_srcdir .. "gtk/gtktextiter.c",
    libGtk_srcdir .. "gtk/gtktextlayout.c",
    libGtk_srcdir .. "gtk/gtktextmark.c",
    libGtk_srcdir .. "gtk/gtktextsegment.c",
    libGtk_srcdir .. "gtk/gtktexttag.c",
    libGtk_srcdir .. "gtk/gtktexttagtable.c",
    libGtk_srcdir .. "gtk/gtktexttypes.c",
    libGtk_srcdir .. "gtk/gtktextutil.c",
    libGtk_srcdir .. "gtk/gtktextview.c",
    libGtk_srcdir .. "gtk/gtktogglebutton.c",
    libGtk_srcdir .. "gtk/gtktoggletoolbutton.c",
    libGtk_srcdir .. "gtk/gtktoolbar.c",
    libGtk_srcdir .. "gtk/gtktoolbutton.c",
    libGtk_srcdir .. "gtk/gtktoolitem.c",
    libGtk_srcdir .. "gtk/gtktoolitemgroup.c",
    libGtk_srcdir .. "gtk/gtktoolpalette.c",
    libGtk_srcdir .. "gtk/gtktoolshell.c",
    libGtk_srcdir .. "gtk/gtktooltip.c",
    libGtk_srcdir .. "gtk/gtktooltipwindow.c",
    libGtk_srcdir .. "gtk/gtktrashmonitor.c",
    libGtk_srcdir .. "gtk/gtktreedatalist.c",
    libGtk_srcdir .. "gtk/gtktreednd.c",
    libGtk_srcdir .. "gtk/gtktreemenu.c",
    libGtk_srcdir .. "gtk/gtktreemodel.c",
    libGtk_srcdir .. "gtk/gtktreemodelfilter.c",
    libGtk_srcdir .. "gtk/gtktreemodelsort.c",
    libGtk_srcdir .. "gtk/gtktreeselection.c",
    libGtk_srcdir .. "gtk/gtktreesortable.c",
    libGtk_srcdir .. "gtk/gtktreestore.c",
    libGtk_srcdir .. "gtk/gtktreeview.c",
    libGtk_srcdir .. "gtk/gtktreeviewcolumn.c",
    libGtk_srcdir .. "gtk/gtkutils.c",
    libGtk_srcdir .. "gtk/gtkutils.c",
    libGtk_srcdir .. "gtk/gtkviewport.c",
    libGtk_srcdir .. "gtk/gtkvolumebutton.c",
    libGtk_srcdir .. "gtk/gtkwidget.c",
    libGtk_srcdir .. "gtk/gtkwidgetpath.c",
    libGtk_srcdir .. "gtk/gtkwin32draw.c",
    libGtk_srcdir .. "gtk/gtkwin32theme.c",
    libGtk_srcdir .. "gtk/gtkwindow.c",
    libGtk_srcdir .. "gtk/gtkwindowgroup.c",
    libGtk_srcdir .. "gtk/gtkxembed.c",
    libGtk_srcdir .. "gtk/inspector/action-editor.c",
    libGtk_srcdir .. "gtk/inspector/actions.c",
    libGtk_srcdir .. "gtk/inspector/cellrenderergraph.c",
    libGtk_srcdir .. "gtk/inspector/css-editor.c",
    libGtk_srcdir .. "gtk/inspector/css-node-tree.c",
    libGtk_srcdir .. "gtk/inspector/data-list.c",
    libGtk_srcdir .. "gtk/inspector/general.c",
    libGtk_srcdir .. "gtk/inspector/gestures.c",
    libGtk_srcdir .. "gtk/inspector/graphdata.c",
    libGtk_srcdir .. "gtk/inspector/gtkstackcombo.c",
    libGtk_srcdir .. "gtk/inspector/gtktreemodelcssnode.c",
    libGtk_srcdir .. "gtk/inspector/init.c",
    libGtk_srcdir .. "gtk/inspector/inspect-button.c",
    libGtk_srcdir .. "gtk/inspector/magnifier.c",
    libGtk_srcdir .. "gtk/inspector/menu.c",
    libGtk_srcdir .. "gtk/inspector/misc-info.c",
    libGtk_srcdir .. "gtk/inspector/object-hierarchy.c",
    libGtk_srcdir .. "gtk/inspector/object-tree.c",
    libGtk_srcdir .. "gtk/inspector/prop-editor.c",
    libGtk_srcdir .. "gtk/inspector/prop-list.c",
    libGtk_srcdir .. "gtk/inspector/resource-list.c",
    libGtk_srcdir .. "gtk/inspector/selector.c",
    libGtk_srcdir .. "gtk/inspector/signals-list.c",
    libGtk_srcdir .. "gtk/inspector/size-groups.c",
    libGtk_srcdir .. "gtk/inspector/statistics.c",
    libGtk_srcdir .. "gtk/inspector/strv-editor.c",
    libGtk_srcdir .. "gtk/inspector/treewalk.c",
    libGtk_srcdir .. "gtk/inspector/visual.c",
    libGtk_srcdir .. "gtk/inspector/window.c",
    libGtk_srcdir .. "modules/input/gtkimcontextmultipress.c",
    libGtk_srcdir .. "modules/input/gtkimcontextthai.c",
    libGtk_srcdir .. "modules/input/gtkimcontextxim.c",
    libGtk_srcdir .. "modules/input/imam-et.c",
    libGtk_srcdir .. "modules/input/imcedilla.c",
    libGtk_srcdir .. "modules/input/imcyrillic-translit.c",
    libGtk_srcdir .. "modules/input/iminuktitut.c",
    libGtk_srcdir .. "modules/input/imipa.c",
    libGtk_srcdir .. "modules/input/immultipress.c",
    libGtk_srcdir .. "modules/input/imthai.c",
    libGtk_srcdir .. "modules/input/imti-er.c",
    libGtk_srcdir .. "modules/input/imti-et.c",
    libGtk_srcdir .. "modules/input/imviqr.c",
    libGtk_srcdir .. "modules/input/imxim.c",
    libGtk_srcdir .. "modules/input/thai-charprop.c",
    libGtk_srcdir .. "modules/printbackends/file/gtkprintbackendfile.c",
}
if os.host() == "linux" then
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gdk/gdkenumtypes.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gdk/gdkmarshalers.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gdk/gdkresources.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gtk/gtkdbusgenerated.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gtk/gtkmarshalers.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gtk/gtkprivatetypebuiltins.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gtk/gtkresources.c")
    table.insert(libGtk_sources, libGtk_extradir .. "linux/gtk/gtktypebuiltins.c")
end
