// Fyleria Engine
// Copyright © 2016 Go Go Gecko Productions

#include "Config/Config.h"
#include "Config/ConfigManager.h"
#include "Utility/Macros.h"
#include "Utility/Python.h"

namespace Gecko
{

ConfigManager* GetConfigManager() { return ConfigManager::GetInstance(); }

};

PYBIND11_EMBEDDED_MODULE(GeckoConfig, m)
{
    // Config.h
    PyBindClass<Gecko::Config, Gecko::SerializableToJson>(m, "Config")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_CONSTRUCTOR_ARGS(const Gecko::String&)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(PythonLib, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorChestFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorFeetFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorFingerFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorHandsFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorHeadFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorNeckFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorLegsFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemArmorShieldFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientBarFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientClothFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientCrystalFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientLeatherFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientMailFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientPlateFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientScaleFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientScrewFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientSheetFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientStudFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemIngredientThreadFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemPotionEnergyFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemPotionHealFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemPotionMagicFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemPotionSpeedFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemWeaponBluntFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemWeaponMageFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemWeaponPierceFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(ItemWeaponSlashFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityBloodFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityDarkFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityEarthFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityFireFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityFleshFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityForceFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityHolyFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityIceFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityLightFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityMindFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityShockFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAffinityWindFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAlchemyAlchemistFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAlchemyChemistFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAlchemyEnergistFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillAlchemyHealerFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownBowbaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownGoldbaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownHammerbaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownPlatebaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownScalebaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownShieldbaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownSpellbaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownStudRemoverFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownSwordbaneFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillBreakdownThreadbareFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatAmbidextrousFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatAvatarFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatBarbarianFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatBlademasterFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatFocusedFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatMageFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatRogueFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCombatStalwartFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingBowsmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingGoldsmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingHammersmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingPlatesmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingScalesmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingShieldsmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingSpellsmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingSwordsmithFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingTannerFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillCraftingWeaverFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponBashFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponBlockFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponBreakFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponCleaveFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponCounterFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponCrackFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponCriticalShotFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponCrushFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponDecapitateFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponDodgeFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponDrillFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponImpactFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponImpaleFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponParryFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponPierceFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponRiposteFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponRushFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponSeverFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponShootFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponSlashFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponSliceFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponSlitFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponSmashFile, Gecko::Config)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(SkillWeaponStealthStrikeFile, Gecko::Config)
    ;
    PyBindVector<Gecko::ConfigArray>(m, "ConfigArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertConfigToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertConfigArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetConfigFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetConfigArrayFromJsonString, Gecko);

    // ConfigManager.h
    PyBindClass<Gecko::ConfigManager>(m, "ConfigManager")
        WRAPPING_ADD_METHOD_SIMPLE(LoadConfig, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(DoesConfigExist, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_POLICY(GetConfig, Gecko::ConfigManager, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetCurrentConfig, Gecko::ConfigManager, PyBindReturnCopy)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(PythonLib, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_READONLY_SIMPLE(PythonLibW, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CurrentConfigName, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(UserConfigFile, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(UserConfigFolder, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(UserDataFolder, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(UserCacheFolder, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WebFolder, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WebHostname, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(RestUrl, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WebsocketUrl, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(StartFullscreen, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AllowScrollbars, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AllowContextMenu, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ScreenWidth, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ScreenHeight, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(RestPort, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WebsocketPort, Gecko::ConfigManager)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ServerThreads, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsPosix, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsWindows, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsWindows32, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsWindows64, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsLinux, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsLinux32, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsLinux64, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsMac, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsIOS, Gecko::ConfigManager)
        WRAPPING_ADD_METHOD_SIMPLE(IsAndroid, Gecko::ConfigManager)
    ;

    // Local
    WRAPPING_STANDALONE_METHOD_POLICY(GetConfigManager, Gecko, PyBindReturnAutoRef);
}
