-- Configuration
libGlib_extradir = "Libs/Glib/extra/"
libGlib_origdir = "Libs/Glib/orig/"
libGlib_srcdir = libGlib_origdir
libGlib_incdir = libGlib_origdir

-- Includes
libGlib_includedirs = {
    libGlib_incdir,
    libGlib_incdir .. "gio/",
    libGlib_incdir .. "gio/xdgmime/",
    libGlib_incdir .. "glib/",
    libGlib_incdir .. "gmodule/",
    libGlib_incdir .. "gobject/",
}
if os.host() == "linux" then
    table.insert(libGlib_includedirs, "/usr/include/libmount")
    table.insert(libGlib_includedirs, "/usr/include/blkid")
    table.insert(libGlib_includedirs, "/usr/include/uuid")
    table.insert(libGlib_includedirs, libGlib_extradir .. "linux/")
    table.insert(libGlib_includedirs, libGlib_extradir .. "linux/gio/")
    table.insert(libGlib_includedirs, libGlib_extradir .. "linux/glib/")
    table.insert(libGlib_includedirs, libGlib_extradir .. "linux/gmodule/")
    table.insert(libGlib_includedirs, libGlib_extradir .. "linux/gobject/")
end

-- Defines
libGlib_defines = {
    "_FILE_OFFSET_BITS=64",
    "_GNU_SOURCE",
    "GLIB_COMPILATION",
    "GIO_COMPILATION",
    "GOBJECT_COMPILATION",
    "GLIB_CHARSETALIAS_DIR=\"lib\"",
    "GIO_MODULE_DIR=\"modules\"",
    "XDG_PREFIX=_gio_xdg"
}
libGlib_debugdefines = {
    "G_ENABLE_DEBUG"
}
libGlib_releasedefines = {
}

-- Options
libGlib_buildoptions = {
    "-std=gnu89",
    "-fno-strict-aliasing"
}
libGlib_linkoptions = {
}

-- Libs
libGlib_libs = {
}

-- Sources
libGlib_sources = {
    libGlib_srcdir .. "glib/deprecated/gallocator.c",
    libGlib_srcdir .. "glib/deprecated/gcache.c",
    libGlib_srcdir .. "glib/deprecated/gcompletion.c",
    libGlib_srcdir .. "glib/deprecated/grel.c",
    libGlib_srcdir .. "glib/deprecated/gthread-deprecated.c",
    libGlib_srcdir .. "glib/garcbox.c",
    libGlib_srcdir .. "glib/garray.c",
    libGlib_srcdir .. "glib/gasyncqueue.c",
    libGlib_srcdir .. "glib/gatomic.c",
    libGlib_srcdir .. "glib/gbacktrace.c",
    libGlib_srcdir .. "glib/gbase64.c",
    libGlib_srcdir .. "glib/gbitlock.c",
    libGlib_srcdir .. "glib/gbookmarkfile.c",
    libGlib_srcdir .. "glib/gbytes.c",
    libGlib_srcdir .. "glib/gcharset.c",
    libGlib_srcdir .. "glib/gchecksum.c",
    libGlib_srcdir .. "glib/gconvert.c",
    libGlib_srcdir .. "glib/gdataset.c",
    libGlib_srcdir .. "glib/gdate.c",
    libGlib_srcdir .. "glib/gdatetime.c",
    libGlib_srcdir .. "glib/gdir.c",
    libGlib_srcdir .. "glib/genviron.c",
    libGlib_srcdir .. "glib/gerror.c",
    libGlib_srcdir .. "glib/gfileutils.c",
    libGlib_srcdir .. "glib/ggettext.c",
    libGlib_srcdir .. "glib/ghash.c",
    libGlib_srcdir .. "glib/ghmac.c",
    libGlib_srcdir .. "glib/ghook.c",
    libGlib_srcdir .. "glib/ghostutils.c",
    libGlib_srcdir .. "glib/giochannel.c",
    libGlib_srcdir .. "glib/giounix.c",
    libGlib_srcdir .. "glib/gkeyfile.c",
    libGlib_srcdir .. "glib/glib-init.c",
    libGlib_srcdir .. "glib/glib-private.c",
    libGlib_srcdir .. "glib/glib-unix.c",
    libGlib_srcdir .. "glib/glist.c",
    libGlib_srcdir .. "glib/gmain.c",
    libGlib_srcdir .. "glib/gmappedfile.c",
    libGlib_srcdir .. "glib/gmarkup.c",
    libGlib_srcdir .. "glib/gmem.c",
    libGlib_srcdir .. "glib/gmessages.c",
    libGlib_srcdir .. "glib/gnode.c",
    libGlib_srcdir .. "glib/goption.c",
    libGlib_srcdir .. "glib/gpattern.c",
    libGlib_srcdir .. "glib/gpoll.c",
    libGlib_srcdir .. "glib/gprimes.c",
    libGlib_srcdir .. "glib/gprintf.c",
    libGlib_srcdir .. "glib/gqsort.c",
    libGlib_srcdir .. "glib/gquark.c",
    libGlib_srcdir .. "glib/gqueue.c",
    libGlib_srcdir .. "glib/grand.c",
    libGlib_srcdir .. "glib/grcbox.c",
    libGlib_srcdir .. "glib/grefcount.c",
    libGlib_srcdir .. "glib/grefstring.c",
    libGlib_srcdir .. "glib/gregex.c",
    libGlib_srcdir .. "glib/gscanner.c",
    libGlib_srcdir .. "glib/gsequence.c",
    libGlib_srcdir .. "glib/gshell.c",
    libGlib_srcdir .. "glib/gslice.c",
    libGlib_srcdir .. "glib/gslist.c",
    libGlib_srcdir .. "glib/gspawn.c",
    libGlib_srcdir .. "glib/gstdio.c",
    libGlib_srcdir .. "glib/gstrfuncs.c",
    libGlib_srcdir .. "glib/gstring.c",
    libGlib_srcdir .. "glib/gstringchunk.c",
    libGlib_srcdir .. "glib/gtester.c",
    libGlib_srcdir .. "glib/gtestutils.c",
    libGlib_srcdir .. "glib/gthread.c",
    libGlib_srcdir .. "glib/gthreadpool.c",
    libGlib_srcdir .. "glib/gthread-posix.c",
    libGlib_srcdir .. "glib/gtimer.c",
    libGlib_srcdir .. "glib/gtimezone.c",
    libGlib_srcdir .. "glib/gtranslit.c",
    libGlib_srcdir .. "glib/gtrashstack.c",
    libGlib_srcdir .. "glib/gtree.c",
    libGlib_srcdir .. "glib/gunibreak.c",
    libGlib_srcdir .. "glib/gunicollate.c",
    libGlib_srcdir .. "glib/gunidecomp.c",
    libGlib_srcdir .. "glib/guniprop.c",
    libGlib_srcdir .. "glib/gurifuncs.c",
    libGlib_srcdir .. "glib/gutf8.c",
    libGlib_srcdir .. "glib/gutils.c",
    libGlib_srcdir .. "glib/guuid.c",
    libGlib_srcdir .. "glib/gvariant.c",
    libGlib_srcdir .. "glib/gvariant-core.c",
    libGlib_srcdir .. "glib/gvariant-parser.c",
    libGlib_srcdir .. "glib/gvariant-serialiser.c",
    libGlib_srcdir .. "glib/gvarianttype.c",
    libGlib_srcdir .. "glib/gvarianttypeinfo.c",
    libGlib_srcdir .. "glib/gversion.c",
    libGlib_srcdir .. "glib/gwakeup.c",
    libGlib_srcdir .. "glib/gwakeup.c",
    libGlib_srcdir .. "glib/gwakeup.c",
    libGlib_srcdir .. "glib/libcharset/localcharset.c",
    libGlib_srcdir .. "gio/gaction.c",
    libGlib_srcdir .. "gio/gactiongroup.c",
    libGlib_srcdir .. "gio/gactiongroupexporter.c",
    libGlib_srcdir .. "gio/gactionmap.c",
    libGlib_srcdir .. "gio/gappinfo.c",
    libGlib_srcdir .. "gio/gapplication.c",
    libGlib_srcdir .. "gio/gapplicationcommandline.c",
    libGlib_srcdir .. "gio/gapplicationimpl-dbus.c",
    libGlib_srcdir .. "gio/gasynchelper.c",
    libGlib_srcdir .. "gio/gasyncinitable.c",
    libGlib_srcdir .. "gio/gasyncresult.c",
    libGlib_srcdir .. "gio/gbufferedinputstream.c",
    libGlib_srcdir .. "gio/gbufferedoutputstream.c",
    libGlib_srcdir .. "gio/gbytesicon.c",
    libGlib_srcdir .. "gio/gcancellable.c",
    libGlib_srcdir .. "gio/gcharsetconverter.c",
    libGlib_srcdir .. "gio/gcontenttype.c",
    libGlib_srcdir .. "gio/gcontextspecificgroup.c",
    libGlib_srcdir .. "gio/gconverter.c",
    libGlib_srcdir .. "gio/gconverterinputstream.c",
    libGlib_srcdir .. "gio/gconverteroutputstream.c",
    libGlib_srcdir .. "gio/gcredentials.c",
    libGlib_srcdir .. "gio/gdatagrambased.c",
    libGlib_srcdir .. "gio/gdatainputstream.c",
    libGlib_srcdir .. "gio/gdataoutputstream.c",
    libGlib_srcdir .. "gio/gdbusactiongroup.c",
    libGlib_srcdir .. "gio/gdbusaddress.c",
    libGlib_srcdir .. "gio/gdbusauth.c",
    libGlib_srcdir .. "gio/gdbusauthmechanismanon.c",
    libGlib_srcdir .. "gio/gdbusauthmechanism.c",
    libGlib_srcdir .. "gio/gdbusauthmechanismexternal.c",
    libGlib_srcdir .. "gio/gdbusauthmechanismsha1.c",
    libGlib_srcdir .. "gio/gdbusauthobserver.c",
    libGlib_srcdir .. "gio/gdbusconnection.c",
    libGlib_srcdir .. "gio/gdbusdaemon.c",
    libGlib_srcdir .. "gio/gdbusdaemon.c",
    libGlib_srcdir .. "gio/gdbuserror.c",
    libGlib_srcdir .. "gio/gdbusinterface.c",
    libGlib_srcdir .. "gio/gdbusinterfaceskeleton.c",
    libGlib_srcdir .. "gio/gdbusintrospection.c",
    libGlib_srcdir .. "gio/gdbusmenumodel.c",
    libGlib_srcdir .. "gio/gdbusmessage.c",
    libGlib_srcdir .. "gio/gdbusmethodinvocation.c",
    libGlib_srcdir .. "gio/gdbusnameowning.c",
    libGlib_srcdir .. "gio/gdbusnamewatching.c",
    libGlib_srcdir .. "gio/gdbusobject.c",
    libGlib_srcdir .. "gio/gdbusobjectmanager.c",
    libGlib_srcdir .. "gio/gdbusobjectmanagerclient.c",
    libGlib_srcdir .. "gio/gdbusobjectmanagerserver.c",
    libGlib_srcdir .. "gio/gdbusobjectproxy.c",
    libGlib_srcdir .. "gio/gdbusobjectskeleton.c",
    libGlib_srcdir .. "gio/gdbusprivate.c",
    libGlib_srcdir .. "gio/gdbusproxy.c",
    libGlib_srcdir .. "gio/gdbusserver.c",
    libGlib_srcdir .. "gio/gdbusutils.c",
    libGlib_srcdir .. "gio/gdelayedsettingsbackend.c",
    libGlib_srcdir .. "gio/gdesktopappinfo.c",
    libGlib_srcdir .. "gio/gdocumentportal.c",
    libGlib_srcdir .. "gio/gdrive.c",
    libGlib_srcdir .. "gio/gdtlsclientconnection.c",
    libGlib_srcdir .. "gio/gdtlsconnection.c",
    libGlib_srcdir .. "gio/gdtlsserverconnection.c",
    libGlib_srcdir .. "gio/gdummyfile.c",
    libGlib_srcdir .. "gio/gdummyproxyresolver.c",
    libGlib_srcdir .. "gio/gdummytlsbackend.c",
    libGlib_srcdir .. "gio/gemblem.c",
    libGlib_srcdir .. "gio/gemblemedicon.c",
    libGlib_srcdir .. "gio/gfdonotificationbackend.c",
    libGlib_srcdir .. "gio/gfileattribute.c",
    libGlib_srcdir .. "gio/gfile.c",
    libGlib_srcdir .. "gio/gfiledescriptorbased.c",
    libGlib_srcdir .. "gio/gfileenumerator.c",
    libGlib_srcdir .. "gio/gfileicon.c",
    libGlib_srcdir .. "gio/gfileinfo.c",
    libGlib_srcdir .. "gio/gfileinputstream.c",
    libGlib_srcdir .. "gio/gfileiostream.c",
    libGlib_srcdir .. "gio/gfilemonitor.c",
    libGlib_srcdir .. "gio/gfilenamecompleter.c",
    libGlib_srcdir .. "gio/gfileoutputstream.c",
    libGlib_srcdir .. "gio/gfilterinputstream.c",
    libGlib_srcdir .. "gio/gfilteroutputstream.c",
    libGlib_srcdir .. "gio/ggtknotificationbackend.c",
    libGlib_srcdir .. "gio/ghttpproxy.c",
    libGlib_srcdir .. "gio/gicon.c",
    libGlib_srcdir .. "gio/ginetaddress.c",
    libGlib_srcdir .. "gio/ginetaddressmask.c",
    libGlib_srcdir .. "gio/ginetsocketaddress.c",
    libGlib_srcdir .. "gio/ginitable.c",
    libGlib_srcdir .. "gio/ginputstream.c",
    libGlib_srcdir .. "gio/gioerror.c",
    libGlib_srcdir .. "gio/giomodule.c",
    libGlib_srcdir .. "gio/giomodule-priv.c",
    libGlib_srcdir .. "gio/giomodule-priv.c",
    libGlib_srcdir .. "gio/gioscheduler.c",
    libGlib_srcdir .. "gio/giostream.c",
    libGlib_srcdir .. "gio/gio-tool-cat.c",
    libGlib_srcdir .. "gio/gio-tool-copy.c",
    libGlib_srcdir .. "gio/gio-tool-info.c",
    libGlib_srcdir .. "gio/gio-tool-list.c",
    libGlib_srcdir .. "gio/gio-tool-mime.c",
    libGlib_srcdir .. "gio/gio-tool-mkdir.c",
    libGlib_srcdir .. "gio/gio-tool-monitor.c",
    libGlib_srcdir .. "gio/gio-tool-mount.c",
    libGlib_srcdir .. "gio/gio-tool-move.c",
    libGlib_srcdir .. "gio/gio-tool-open.c",
    libGlib_srcdir .. "gio/gio-tool-remove.c",
    libGlib_srcdir .. "gio/gio-tool-rename.c",
    libGlib_srcdir .. "gio/gio-tool-save.c",
    libGlib_srcdir .. "gio/gio-tool-set.c",
    libGlib_srcdir .. "gio/gio-tool-trash.c",
    libGlib_srcdir .. "gio/gio-tool-tree.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmime.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimealias.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimecache.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeglob.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeicon.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeint.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimemagic.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeparent.c",
    libGlib_srcdir .. "gio/gkeyfilesettingsbackend.c",
    libGlib_srcdir .. "gio/glistmodel.c",
    libGlib_srcdir .. "gio/gliststore.c",
    libGlib_srcdir .. "gio/gloadableicon.c",
    libGlib_srcdir .. "gio/glocalfile.c",
    libGlib_srcdir .. "gio/glocalfileenumerator.c",
    libGlib_srcdir .. "gio/glocalfileinfo.c",
    libGlib_srcdir .. "gio/glocalfileinputstream.c",
    libGlib_srcdir .. "gio/glocalfileiostream.c",
    libGlib_srcdir .. "gio/glocalfilemonitor.c",
    libGlib_srcdir .. "gio/glocalfileoutputstream.c",
    libGlib_srcdir .. "gio/glocalvfs.c",
    libGlib_srcdir .. "gio/gmarshal-internal.c",
    libGlib_srcdir .. "gio/gmemoryinputstream.c",
    libGlib_srcdir .. "gio/gmemoryoutputstream.c",
    libGlib_srcdir .. "gio/gmemorysettingsbackend.c",
    libGlib_srcdir .. "gio/gmenu.c",
    libGlib_srcdir .. "gio/gmenuexporter.c",
    libGlib_srcdir .. "gio/gmenumodel.c",
    libGlib_srcdir .. "gio/gmount.c",
    libGlib_srcdir .. "gio/gmountoperation.c",
    libGlib_srcdir .. "gio/gnativesocketaddress.c",
    libGlib_srcdir .. "gio/gnativevolumemonitor.c",
    libGlib_srcdir .. "gio/gnetworkaddress.c",
    libGlib_srcdir .. "gio/gnetworking.c",
    libGlib_srcdir .. "gio/gnetworkmonitorbase.c",
    libGlib_srcdir .. "gio/gnetworkmonitor.c",
    libGlib_srcdir .. "gio/gnetworkmonitornetlink.c",
    libGlib_srcdir .. "gio/gnetworkmonitornm.c",
    libGlib_srcdir .. "gio/gnetworkmonitorportal.c",
    libGlib_srcdir .. "gio/gnetworkservice.c",
    libGlib_srcdir .. "gio/gnotificationbackend.c",
    libGlib_srcdir .. "gio/gnotification.c",
    libGlib_srcdir .. "gio/gnullsettingsbackend.c",
    libGlib_srcdir .. "gio/gopenuriportal.c",
    libGlib_srcdir .. "gio/goutputstream.c",
    libGlib_srcdir .. "gio/gpermission.c",
    libGlib_srcdir .. "gio/gpollableinputstream.c",
    libGlib_srcdir .. "gio/gpollableoutputstream.c",
    libGlib_srcdir .. "gio/gpollableutils.c",
    libGlib_srcdir .. "gio/gpollfilemonitor.c",
    libGlib_srcdir .. "gio/gportalnotificationbackend.c",
    libGlib_srcdir .. "gio/gportalsupport.c",
    libGlib_srcdir .. "gio/gpropertyaction.c",
    libGlib_srcdir .. "gio/gproxyaddress.c",
    libGlib_srcdir .. "gio/gproxyaddressenumerator.c",
    libGlib_srcdir .. "gio/gproxy.c",
    libGlib_srcdir .. "gio/gproxyresolver.c",
    libGlib_srcdir .. "gio/gproxyresolverportal.c",
    libGlib_srcdir .. "gio/gremoteactiongroup.c",
    libGlib_srcdir .. "gio/gresolver.c",
    libGlib_srcdir .. "gio/gresource.c",
    libGlib_srcdir .. "gio/gresourcefile.c",
    libGlib_srcdir .. "gio/gseekable.c",
    libGlib_srcdir .. "gio/gsettingsbackend.c",
    libGlib_srcdir .. "gio/gsettings.c",
    libGlib_srcdir .. "gio/gsettings-mapping.c",
    libGlib_srcdir .. "gio/gsettingsschema.c",
    libGlib_srcdir .. "gio/gsimpleaction.c",
    libGlib_srcdir .. "gio/gsimpleactiongroup.c",
    libGlib_srcdir .. "gio/gsimpleasyncresult.c",
    libGlib_srcdir .. "gio/gsimpleiostream.c",
    libGlib_srcdir .. "gio/gsimplepermission.c",
    libGlib_srcdir .. "gio/gsimpleproxyresolver.c",
    libGlib_srcdir .. "gio/gsocketaddress.c",
    libGlib_srcdir .. "gio/gsocketaddressenumerator.c",
    libGlib_srcdir .. "gio/gsocket.c",
    libGlib_srcdir .. "gio/gsocketclient.c",
    libGlib_srcdir .. "gio/gsocketconnectable.c",
    libGlib_srcdir .. "gio/gsocketconnection.c",
    libGlib_srcdir .. "gio/gsocketcontrolmessage.c",
    libGlib_srcdir .. "gio/gsocketinputstream.c",
    libGlib_srcdir .. "gio/gsocketlistener.c",
    libGlib_srcdir .. "gio/gsocketoutputstream.c",
    libGlib_srcdir .. "gio/gsocketservice.c",
    libGlib_srcdir .. "gio/gsocks4aproxy.c",
    libGlib_srcdir .. "gio/gsocks4proxy.c",
    libGlib_srcdir .. "gio/gsocks5proxy.c",
    libGlib_srcdir .. "gio/gsrvtarget.c",
    libGlib_srcdir .. "gio/gsubprocess.c",
    libGlib_srcdir .. "gio/gsubprocesslauncher.c",
    libGlib_srcdir .. "gio/gtask.c",
    libGlib_srcdir .. "gio/gtcpconnection.c",
    libGlib_srcdir .. "gio/gtcpwrapperconnection.c",
    libGlib_srcdir .. "gio/gtestdbus.c",
    libGlib_srcdir .. "gio/gthemedicon.c",
    libGlib_srcdir .. "gio/gthreadedresolver.c",
    libGlib_srcdir .. "gio/gthreadedsocketservice.c",
    libGlib_srcdir .. "gio/gtlsbackend.c",
    libGlib_srcdir .. "gio/gtlscertificate.c",
    libGlib_srcdir .. "gio/gtlsclientconnection.c",
    libGlib_srcdir .. "gio/gtlsconnection.c",
    libGlib_srcdir .. "gio/gtlsdatabase.c",
    libGlib_srcdir .. "gio/gtlsfiledatabase.c",
    libGlib_srcdir .. "gio/gtlsinteraction.c",
    libGlib_srcdir .. "gio/gtlspassword.c",
    libGlib_srcdir .. "gio/gtlsserverconnection.c",
    libGlib_srcdir .. "gio/gtrashportal.c",
    libGlib_srcdir .. "gio/gunionvolumemonitor.c",
    libGlib_srcdir .. "gio/gunixconnection.c",
    libGlib_srcdir .. "gio/gunixcredentialsmessage.c",
    libGlib_srcdir .. "gio/gunixfdlist.c",
    libGlib_srcdir .. "gio/gunixfdmessage.c",
    libGlib_srcdir .. "gio/gunixinputstream.c",
    libGlib_srcdir .. "gio/gunixmount.c",
    libGlib_srcdir .. "gio/gunixmounts.c",
    libGlib_srcdir .. "gio/gunixoutputstream.c",
    libGlib_srcdir .. "gio/gunixsocketaddress.c",
    libGlib_srcdir .. "gio/gunixvolume.c",
    libGlib_srcdir .. "gio/gunixvolumemonitor.c",
    libGlib_srcdir .. "gio/gvdb/gvdb-builder.c",
    libGlib_srcdir .. "gio/gvdb/gvdb-builder.c",
    libGlib_srcdir .. "gio/gvdb/gvdb-reader.c",
    libGlib_srcdir .. "gio/gvfs.c",
    libGlib_srcdir .. "gio/gvolume.c",
    libGlib_srcdir .. "gio/gvolumemonitor.c",
    libGlib_srcdir .. "gio/gzlibcompressor.c",
    libGlib_srcdir .. "gio/gzlibdecompressor.c",
    libGlib_srcdir .. "gio/inotify/ginotifyfilemonitor.c",
    libGlib_srcdir .. "gio/inotify/inotify-helper.c",
    libGlib_srcdir .. "gio/inotify/inotify-kernel.c",
    libGlib_srcdir .. "gio/inotify/inotify-missing.c",
    libGlib_srcdir .. "gio/inotify/inotify-path.c",
    libGlib_srcdir .. "gio/inotify/inotify-sub.c",
    libGlib_srcdir .. "gio/thumbnail-verify.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimealias.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmime.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimecache.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeglob.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeicon.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeint.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimemagic.c",
    libGlib_srcdir .. "gio/xdgmime/xdgmimeparent.c",
    libGlib_srcdir .. "gmodule/gmodule.c",
    libGlib_srcdir .. "gobject/gatomicarray.c",
    libGlib_srcdir .. "gobject/gbinding.c",
    libGlib_srcdir .. "gobject/gboxed.c",
    libGlib_srcdir .. "gobject/gclosure.c",
    libGlib_srcdir .. "gobject/genums.c",
    libGlib_srcdir .. "gobject/gmarshal.c",
    libGlib_srcdir .. "gobject/gobject.c",
    libGlib_srcdir .. "gobject/gparam.c",
    libGlib_srcdir .. "gobject/gparamspecs.c",
    libGlib_srcdir .. "gobject/gsignal.c",
    libGlib_srcdir .. "gobject/gsourceclosure.c",
    libGlib_srcdir .. "gobject/gtype.c",
    libGlib_srcdir .. "gobject/gtypemodule.c",
    libGlib_srcdir .. "gobject/gtypeplugin.c",
    libGlib_srcdir .. "gobject/gvaluearray.c",
    libGlib_srcdir .. "gobject/gvalue.c",
    libGlib_srcdir .. "gobject/gvaluetransform.c",
    libGlib_srcdir .. "gobject/gvaluetypes.c",
    libGlib_srcdir .. "gthread/gthread-impl.c"
}
if os.host() == "linux" then
    table.insert(libGlib_sources, libGlib_extradir .. "linux/gobject/glib-enumtypes.c")
    table.insert(libGlib_sources, libGlib_extradir .. "linux/gio/gdbus-daemon-generated.c")
    table.insert(libGlib_sources, libGlib_extradir .. "linux/gio/gioenumtypes.c")
    table.insert(libGlib_sources, libGlib_extradir .. "linux/gio/xdp-dbus.c")
end
