// Fyleria Engine
// Copyright © 2016 Go Go Gecko Productions

#include "Skills/SkillTypes.h"

namespace Gecko
{

MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillFunctionNodeType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillTreeType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillWeaponBaseType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillWeaponType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillAlchemyType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillBreakdownType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillCombatType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillCraftingType);
MAKE_ENUM_GETSTRINGARRAY_IMPL(SkillAffinityType);

MAKE_ENUM_CONVERTERS_IMPL(SkillFunctionNodeType);
MAKE_ENUM_CONVERTERS_IMPL(SkillTreeType);
MAKE_ENUM_CONVERTERS_IMPL(SkillWeaponBaseType);
MAKE_ENUM_CONVERTERS_IMPL(SkillWeaponType);
MAKE_ENUM_CONVERTERS_IMPL(SkillAlchemyType);
MAKE_ENUM_CONVERTERS_IMPL(SkillBreakdownType);
MAKE_ENUM_CONVERTERS_IMPL(SkillCombatType);
MAKE_ENUM_CONVERTERS_IMPL(SkillCraftingType);
MAKE_ENUM_CONVERTERS_IMPL(SkillAffinityType);

};
