/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "gdk-pixbuf"

#define HAVE_BIND_TEXTDOMAIN_CODESET 1

#define HAVE_LRINT 1

#define HAVE_ROUND 1

#define HAVE_SETRLIMIT 1

#define HAVE_SIGSETJMP

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_UNISTD_H 1

#define OS_LINUX 1

#define USE_GMODULE

