/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ALIGNOF_CHAR 1

#define ALIGNOF_DBIND_POINTER 8

#define ALIGNOF_DBIND_STRUCT 1

#define ALIGNOF_DBUS_BOOL_T 4

#define ALIGNOF_DBUS_INT16_T 2

#define ALIGNOF_DBUS_INT32_T 4

#define ALIGNOF_DBUS_INT64_T 8

#define ALIGNOF_DOUBLE 8

#define GETTEXT_PACKAGE at-spi2-core

#define HAVE_X11 1

#define HAVE_XKB 1

