// Fyleria Engine
// Copyright © 2019 Go Go Gecko Productions

// Internal includes
#include "CharacterData/CharacterActionData.h"
#include "CharacterData/CharacterBasicData.h"
#include "CharacterData/CharacterBattleData.h"
#include "CharacterData/CharacterProgressData.h"
#include "CharacterData/CharacterSkillData.h"
#include "CharacterData/CharacterStatChangeData.h"
#include "Utility/Macros.h"
#include "Utility/Python.h"

PYBIND11_MAKE_OPAQUE(Gecko::CharacterActionDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterBasicDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterBattleDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterProgressDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterSkillDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterStatChangeDataArray);

PYBIND11_EMBEDDED_MODULE(GeckoCharacterData, m)
{
    // CharacterActionData.h
    PyBindClass<Gecko::CharacterActionData>(m, "CharacterActionData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AvailableActions, Gecko::CharacterActionData)
    ;
    PyBindVector<Gecko::CharacterActionDataArray>(m, "CharacterActionDataArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterActionDataToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterActionDataArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterActionDataFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterActionDataArrayFromJsonString, Gecko);

    // CharacterBasicData.h
    PyBindClass<Gecko::CharacterBasicData, Gecko::StatTypeHolder>(m, "CharacterBasicData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CharacterID, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PartyID, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(FirstName, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(LastName, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Gender, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Hair, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Eyes, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Handedness, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BaseRace, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(TransformedRace, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PowerSet, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponSet, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Age, Gecko::CharacterBasicData)
    ;
    PyBindVector<Gecko::CharacterBasicDataArray>(m, "CharacterBasicDataArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterBasicDataToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterBasicDataArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterBasicDataFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterBasicDataArrayFromJsonString, Gecko);

    // CharacterBattleData.h
    PyBindClass<Gecko::CharacterBattleData, Gecko::StatTypeHolder>(m, "CharacterBattleData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyNewStatus, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyGivenDamage, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyTakenDamage, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(AdvanceRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(FinishBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(CanRegenerateFromStat, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateEquipmentRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ResolveTargetPlaceholder, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetPrimaryWeaponRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSecondaryWeaponRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetPrimaryShieldRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSecondaryShieldRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourceThisAction, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MostRecentActionSource, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PreviousActionTypes, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsThisAction, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsLastRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourcesThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourcesLastRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MostRecentActionTargets, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IsDead, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IsUnconscious, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AttackCounter, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefendCounter, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageTakenThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageTakenThisBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageGivenThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageGivenThisBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AllowedTargetAmount, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponLeftBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponLeftPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponLeftSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponRightBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponRightPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponRightSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChanceToCauseCriticalHit, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChanceToBlockCriticalHit, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalHitMultiplier, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChanceToApplyMultipleAttacks, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AttacksMultiplier, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponPrimaryDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponPrimaryDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponSecondaryDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponSecondaryDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GeneralDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GeneralDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefensivePowerEffectsBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefensivePowerEffectsBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OffensivePowerEffectsBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OffensivePowerEffectsBonusPercent, Gecko::CharacterBattleData)
    ;
    PyBindVector<Gecko::CharacterBattleDataArray>(m, "CharacterBattleDataArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterBattleDataToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterBattleDataArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterBattleDataFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterBattleDataArrayFromJsonString, Gecko);

    // CharacterProgressData.h
    PyBindClass<Gecko::CharacterProgressData, Gecko::StatTypeHolder>(m, "CharacterProgressData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyTakenDamage, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyRegeneration, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyActionCost, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateAvailableAP, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Speed, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmberValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RubyValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DiamondValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CitrineValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OnyxValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(QuartzValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SapphireValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmethystValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EmeraldValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GarnetValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IvoryValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OpalValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SeverPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlicePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlitPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CleavePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DecapitatePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ParryPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RipostePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BashPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SmashPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpactPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrushPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BreakPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrackPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlockPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RushPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PiercePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DrillPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShootPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpalePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrikePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShotPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DodgePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CounterPoints, Gecko::CharacterProgressData)
    ;
    PyBindVector<Gecko::CharacterProgressDataArray>(m, "CharacterProgressDataArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterProgressDataToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterProgressDataArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterProgressDataFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterProgressDataArrayFromJsonString, Gecko);

    // CharacterSkillData.h
    PyBindClass<Gecko::CharacterSkillData>(m, "CharacterSkillData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(SetAllSkillCurrentValues, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(SetAllSkillRankValues, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateUsedSkills, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateSkillRanking, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(AddSkillUse, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSkillUseCount, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BarbarianCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BarbarianRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MageCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MageRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RogueCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RogueRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlademasterCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlademasterRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AvatarCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AvatarRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmbidextrousCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmbidextrousRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FocusedCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FocusedRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StalwartCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StalwartRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SeverCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SeverRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SliceCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SliceRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlitCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlitRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CleaveCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CleaveRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DecapitateCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DecapitateRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ParryCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ParryRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RiposteCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RiposteRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BashCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BashRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SmashCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SmashRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrushCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrushRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpactCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpactRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BreakCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BreakRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrackCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrackRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlockCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlockRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RushCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RushRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DrillCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DrillRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShootCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShootRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpaleCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpaleRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrikeCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrikeRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShotCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShotRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DodgeCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DodgeRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CounterCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CounterRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealerCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealerRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AlchemistCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AlchemistRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergistCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergistRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChemistCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChemistRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammersmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammersmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellsmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellsmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowsmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowsmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordsmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordsmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaverCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaverRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(TannerCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(TannerRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalesmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalesmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatesmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatesmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldsmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldsmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldsmithCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldsmithRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammerbaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HammerbaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellbaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SpellbaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowbaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BowbaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordbaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SwordbaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ThreadbareCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ThreadbareRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StudRemoverCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StudRemoverRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalebaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ScalebaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatebaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PlatebaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldbaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GoldbaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldbaneCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShieldbaneRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HolyCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HolyRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FireCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FireRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IceCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IceRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShockCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShockRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DarkCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DarkRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(LightCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(LightRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ForceCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ForceRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MindCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MindRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EarthCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EarthRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BloodCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BloodRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FleshCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(FleshRank, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WindCurrent, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WindRank, Gecko::CharacterSkillData)
    ;
    PyBindVector<Gecko::CharacterSkillDataArray>(m, "CharacterSkillDataArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterSkillDataToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterSkillDataArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterSkillDataFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterSkillDataArrayFromJsonString, Gecko);

    // CharacterStatChangeData.h
    PyBindClass<Gecko::CharacterStatChangeData>(m, "CharacterStatChangeData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_POLICY(GetPassiveChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActiveChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActionableChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_SIMPLE(AddProlongedStatChange, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveProlongedStatChange, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY(GetProlongedStatChange, Gecko::CharacterStatChangeData, PyBindReturnRefInternal, const Gecko::String&)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY_CONST(GetProlongedStatChange, Gecko::CharacterStatChangeData, PyBindReturnCopy, const Gecko::String&)
        WRAPPING_ADD_METHOD_SIMPLE(GetProlongedStatChangeEntries, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(DoesProlongedStatChangeExist, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(HasProlongedStatChangeExpired, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveAllExpiredProlongedStatChanges, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProlongedStatChanges, Gecko::CharacterStatChangeData)
    ;
    PyBindVector<Gecko::CharacterStatChangeDataArray>(m, "CharacterStatChangeDataArray");
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterStatChangeDataToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(ConvertCharacterStatChangeDataArrayToJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterStatChangeDataFromJsonString, Gecko);
    WRAPPING_STANDALONE_METHOD_SIMPLE(GetCharacterStatChangeDataArrayFromJsonString, Gecko);
}
