// Fyleria Engine
// Copyright (c) 2019 Go Go Gecko Productions. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Internal includes
#include "CharacterData/CharacterActionDataWrapper.h"
#include "Application/Application.h"
#include "Utility/Types.h"

namespace Gecko
{

// Start wrapper
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_START(CharacterData, CharacterActionData);

// Int stats
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(SlashPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(SeverPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(SlicePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(SlitPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(CleavePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(DecapitatePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(ParryPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(RipostePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(BashPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(SmashPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(ImpactPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(CrushPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(BreakPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(CrackPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(BlockPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(RushPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(PiercePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(DrillPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(ShootPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(ImpalePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(StealthStrikePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(CriticalShotPoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(DodgePoints);
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(CounterPoints);

// List of character actions
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_PROPERTY(AvailableActions);

// Finish wrapper
MAKE_JSONDATA_WRAPPER_CLASS_IMPL_END();

};
