// Fyleria Engine
// Copyright © 2019 Go Go Gecko Productions

// Internal includes
#include "CharacterData/CharacterActionData.h"
#include "CharacterData/CharacterBasicData.h"
#include "CharacterData/CharacterBattleData.h"
#include "CharacterData/CharacterProgressData.h"
#include "CharacterData/CharacterSkillData.h"
#include "CharacterData/CharacterStatChangeData.h"
#include "Utility/Macros.h"
#include "Utility/Python.h"

PYBIND11_MAKE_OPAQUE(Gecko::CharacterActionDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterBasicDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterBattleDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterProgressDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterSkillDataArray);
PYBIND11_MAKE_OPAQUE(Gecko::CharacterStatChangeDataArray);

PYBIND11_EMBEDDED_MODULE(GeckoCharacterData, m)
{
    // CharacterActionData.h
    PyBindClass<Gecko::CharacterActionData>(m, "CharacterActionData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterActionData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(AvailableActions, Gecko::CharacterActionData)
    ;
    PyBindVector<Gecko::CharacterActionDataArray>(m, "CharacterActionDataArray");

    // CharacterBasicData.h
    PyBindClass<Gecko::CharacterBasicData>(m, "CharacterBasicData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(CharacterID, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PartyID, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(FirstName, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(LastName, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Gender, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Hair, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Eyes, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(Handedness, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(BaseRace, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(TransformedRace, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PowerSet, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(WeaponSet, Gecko::CharacterBasicData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Age, Gecko::CharacterBasicData)
    ;
    PyBindVector<Gecko::CharacterBasicDataArray>(m, "CharacterBasicDataArray");

    // CharacterBattleData.h
    PyBindClass<Gecko::CharacterBattleData>(m, "CharacterBattleData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyNewStatus, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyGivenDamage, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyTakenDamage, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(AdvanceRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(FinishBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(CanRegenerateFromStat, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateEquipmentRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(ResolveTargetPlaceholder, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetPrimaryWeaponRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSecondaryWeaponRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetPrimaryShieldRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSecondaryShieldRatings, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourceThisAction, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MostRecentActionSource, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PreviousActionTypes, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsThisAction, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionTargetsLastRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourcesThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionSourcesLastRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(MostRecentActionTargets, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IsDead, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IsUnconscious, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AttackCounter, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefendCounter, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageTakenThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageTakenThisBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageGivenThisRound, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DamageGivenThisBattle, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AllowedTargetAmount, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponLeftBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponLeftPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponLeftSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponRightBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponRightPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedWeaponRightSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldLeftMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedShieldRightMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorBluntRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorPierceRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorSlashRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EquippedArmorMagicRating, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChanceToCauseCriticalHit, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChanceToBlockCriticalHit, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalHitMultiplier, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ChanceToApplyMultipleAttacks, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AttacksMultiplier, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponPrimaryDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponPrimaryDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponSecondaryDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(WeaponSecondaryDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GeneralDamageBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GeneralDamageBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefensivePowerEffectsBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DefensivePowerEffectsBonusPercent, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OffensivePowerEffectsBonusValue, Gecko::CharacterBattleData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OffensivePowerEffectsBonusPercent, Gecko::CharacterBattleData)
    ;
    PyBindVector<Gecko::CharacterBattleDataArray>(m, "CharacterBattleDataArray");

    // CharacterProgressData.h
    PyBindClass<Gecko::CharacterProgressData>(m, "CharacterProgressData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyTakenDamage, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyRegeneration, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(ApplyActionCost, Gecko::CharacterProgressData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateAvailableAP, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyPointsCurrent, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyPointsMax, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyRegen, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(HealthCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyCostDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Speed, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmberValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RubyValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DiamondValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CitrineValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OnyxValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(QuartzValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SapphireValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(AmethystValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EmeraldValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(GarnetValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(IvoryValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(OpalValueDelta, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BluntDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(MagicDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PierceDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyAttack, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(EnergyDefense, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlashPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SeverPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlicePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SlitPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CleavePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DecapitatePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ParryPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RipostePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BashPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(SmashPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpactPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrushPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BreakPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CrackPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(BlockPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(RushPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(PiercePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DrillPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ShootPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(ImpalePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrikePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShotPoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(DodgePoints, Gecko::CharacterProgressData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CounterPoints, Gecko::CharacterProgressData)
    ;
    PyBindVector<Gecko::CharacterProgressDataArray>(m, "CharacterProgressDataArray");

    // CharacterSkillData.h
    PyBindClass<Gecko::CharacterSkillData>(m, "CharacterSkillData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSkillCurrentValue, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(GetSkillRankValue, Gecko::CharacterSkillData)
        WRAPPING_ADD_METHOD_SIMPLE(UpdateSkillValue, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Barbarian, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Mage, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Rogue, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Blademaster, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Avatar, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Ambidextrous, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Focused, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Stalwart, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Slash, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Sever, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Slice, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Slit, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Cleave, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Decapitate, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Parry, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Riposte, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Bash, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Smash, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Crush, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Impact, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Break, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Crack, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Block, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Rush, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Pierce, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Drill, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Shoot, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Impale, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StealthStrike, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(CriticalShot, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Dodge, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Counter, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Healer, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Alchemist, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Energist, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Chemist, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Hammersmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Spellsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Bowsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Swordsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Weaver, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Tanner, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Scalesmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Platesmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Goldsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Shieldsmith, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Hammerbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Spellbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Bowbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Swordbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Threadbare, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(StudRemover, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Scalebane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Platebane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Goldbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Shieldbane, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Holy, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Fire, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Ice, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Shock, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Dark, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Light, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Force, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Mind, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Earth, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Blood, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Flesh, Gecko::CharacterSkillData)
        WRAPPING_ADD_BASIC_PROPERTY_SIMPLE(Wind, Gecko::CharacterSkillData)
    ;
    PyBindVector<Gecko::CharacterSkillDataArray>(m, "CharacterSkillDataArray");

    // CharacterStatChangeData.h
    PyBindClass<Gecko::CharacterStatChangeData>(m, "CharacterStatChangeData")
        WRAPPING_ADD_CONSTRUCTOR_SIMPLE()
        WRAPPING_ADD_METHOD_SIMPLE(Clear, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_POLICY(GetPassiveChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActiveChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_POLICY(GetActionableChanges, Gecko::CharacterStatChangeData, PyBindReturnCopy)
        WRAPPING_ADD_METHOD_SIMPLE(AddProlongedStatChange, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveProlongedStatChange, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY(GetProlongedStatChange, Gecko::CharacterStatChangeData, PyBindReturnRefInternal, const Gecko::String&)
        WRAPPING_ADD_METHOD_OVERLOADED_POLICY_CONST(GetProlongedStatChange, Gecko::CharacterStatChangeData, PyBindReturnCopy, const Gecko::String&)
        WRAPPING_ADD_METHOD_SIMPLE(GetProlongedStatChangeEntries, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(DoesProlongedStatChangeExist, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(HasProlongedStatChangeExpired, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_METHOD_SIMPLE(RemoveAllExpiredProlongedStatChanges, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(PassiveItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActiveItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableSkillDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ActionableItemDataArray, Gecko::CharacterStatChangeData)
        WRAPPING_ADD_BASIC_PROPERTY_MULTIGET(ProlongedStatChanges, Gecko::CharacterStatChangeData)
    ;
    PyBindVector<Gecko::CharacterStatChangeDataArray>(m, "CharacterStatChangeDataArray");
}
